---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsNCiAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF5T0MwMk5UcGpNVE0yWkdkRE13PT0iDQogICAgICAgIH0NCiAgICB9DQp9IA==
type: kubernetes.io/dockerconfigjson
