image:
  repository: gitlab.praktikum-services.ru:5050/std-028-65/momo-store/momo-backend
  pullPolicy: Always
  tag: {{TAG}}
replicas: 2
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
rollingUpdate:
  maxUnavailable: 2
  maxSurge: 20%
service:
  port: 8081
imagePullSecrets:
  name: docker-config
  key: .dockerconfigjson
  value: ""
  type: kubernetes.io/dockerconfigjson
