image:
  repository: gitlab.praktikum-services.ru:5050/std-028-65/momo-store/momo-frontend
  pullPolicy: Always
  tag: {{TAG}}
replicas: 2
revisionHistoryLimit: 15
strategy:
  type: RollingUpdate
service:
  port: 80
fqdn: std-028-65-momo-store.ru
imagePullSecrets:
  name: docker-config
  key: .dockerconfigjson
  value: ""
  type: kubernetes.io/dockerconfigjson
